## Homework 2

This homework covers the material in Lessons 3 & 4.  It is due **Thurday, June 15**.  Please submit your **answers as a PDF**.

1\. Modify the LU method (without pivoting) to work **in-place**.  That is, it should not allocate any new memory for L or U, but instead overwrite A.

In [7]:
def LU(A):
    U = np.copy(A)
    m, n = A.shape
    L = np.eye(n)
    for k in range(n-1):
        for j in range(k+1,n):
            L[j,k] = U[j,k]/U[k,k]
            U[j,k:n] -= L[j,k] * U[k,k:n]
    return L, U

In [34]:
def _LU(A):
    U = np.copy(A)
    m, n = A.shape
    for k in range(n-1):
        temp = []
        for j in range(k+1,n):
            temp.append(U[j,k]/U[k,k])
            U[j,k:n] -= temp[-1] * U[k,k:n]
#         print(temp)
        U[k+1:m,k] = temp
        
    return U

In [36]:
import numpy as np 

A = np.array([[1,2,3,5],
              [4,5,6,6],
              [7,8,9,8],
              [10,13,15,0]]).astype(float)
l,u =LU(A)
l , u

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in double_scalars
  import sys
C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in multiply
  


(array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 4.        ,  1.        ,  0.        ,  0.        ],
        [ 7.        ,  2.        ,  1.        ,  0.        ],
        [10.        ,  2.33333333,        -inf,  1.        ]]),
 array([[  1.,   2.,   3.,   5.],
        [  0.,  -3.,  -6., -14.],
        [  0.,   0.,   0.,   1.],
        [  0.,   0.,  nan,  inf]]))

In [37]:
_LU(A)

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in double_scalars
  import sys
C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in multiply
  


array([[  1.        ,   2.        ,   3.        ,   5.        ],
       [  4.        ,  -3.        ,  -6.        , -14.        ],
       [  7.        ,   2.        ,   0.        ,   1.        ],
       [ 10.        ,   2.33333333,         -inf,          inf]])

In [31]:
np.allclose(l - np.diag(np.ones(A.shape[1])) + u, _LU(A))

True

2\. Modify our LU method from class to add pivoting, as described in the lesson.  *Hint: the swap method below will be useful* 

In [ ]:
def swap(a,b):
    temp = np.copy(a)
    a[:] = b
    b[:] = temp

3\. For each of the following sets of dimensions, either
  - give the dimensions of the output of an operation on A and B, **or** 
  - answer *incompatible* if the dimensions are incompatible according to the [numpy rules of broadcasting](https://docs.scipy.org/doc/numpy-1.10.0/user/basics.broadcasting.html).

    a.  A      (2d array):  3 x 3
        B      (1d array):      1

    b.  A      (2d array):      2 x 1
        B      (3d array):  6 x 4 x 2

    c.  A      (2d array):  5 x 4
        B      (1d array):      4

    d.  A      (3d array):  32 x 64 x 8
        B      (3d array):   32 x 1 x 8

    e.  A      (3d array):       64 x 1
        B      (3d array):  32 x 1 x 16

    f.  A      (3d array):  32 x 64 x 2
        B      (3d array):   32 x 1 x 8

4\. Write how this matrix would be stored in compressed row format:

\begin{pmatrix}
  1 & & & & -2 & -3 \\
  & 3 &  & & & -9 \\
  &  &  & -7 & 4 & \\ 
  -1 & 2 & & 7 & & \\
  -3 & & & 26 & &
 \end{pmatrix}
 
\begin{bmatrix}
index & 0 & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11 \\
val & 1 & -2 & -3 & 3 & -9 & -7 & 4 & -1 & 2 & 7 & -3 & 26 \\
RowPtr & 0 & 3 & 5 & 7 & 10 & 12 & - & - & - & - & - & - \\
col & 0 & 3 & 4 & 1 & 4 & 2  & 3 & 0 & 1 & 2 & 0 & 2 \\
\end{bmatrix}